docs: corrected minute grammatical errors in README.md
wasp-lang/wasp pull request #1529
Opened 2023-10-21 19:00 UTC by alienishi

### Description

I have corrected some minute grammatical errors in README.md

### Select what type of change this PR introduces:

1. [x] **Just code/docs improvement** (no functional change). 
2. [ ] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [ ] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

2023-10-21 19:02 UTC, alienishi commented
@Martinsos @sodic 
Please review my PR and if according to the guidelines please do merge it :)

2023-10-23 13:04 UTC, Martinsos requested changes
Thanks for the contribution! I like most of the changes, but some of them need correction I think, I commented on those.

2023-10-23 13:04 UTC, Martinsos commented on README.md
> +query get tasks {
This should be modified.

2023-10-23 13:04 UTC, Martinsos commented on README.md
> +Given a simple .wasp configuration file that describes the high-level details of your web app and .js(x)/.css/..., source files with your unique logic, the Wasp compiler generates the full source of
This doesn't read right.
I think we should `,` right after `...`, not the one you removed.

2023-10-23 13:04 UTC, Martinsos commented on README.md
> +Even if you don't plan to submit any code, just join the discussion on discord [![Discord](https://img.shields.io/discord/686873244791210014?label=chat%20on%20discord)](https://discord.gg/rzdnErX) an
I would revert `join` here to `joining`.

2023-10-23 18:46 UTC, alienishi commented
@Martinsos 
Thanks for the suggestions!
I have made the changes according to your recommendations :)

2023-10-25 09:17 UTC, Martinsos approved these changes

2023-10-25 09:18 UTC, merged

2023-10-25 09:18 UTC, Martinsos commented
Thanks @alienishi , merged!