Fixed links to examples, added examples/README.md, improved some names.
wasp-lang/wasp pull request #1542
Opened 2023-10-27 09:40 UTC by Martinsos

This PR is inspired by https://github.com/wasp-lang/wasp/commit/5e45dad54a5efaf1f4dd74d9a047b72b541f3c79, kind of a follow-up on it.

- I added examples/README.md, that explains for each example what it does and why it is interesting. I know you tried to do it with the names, but I don't think that works as well as it should due to very little space.
- I renamed `gpt-response-streaming` to be just `streaming` since it doesn't do anything with gpt, it just does HTTP streaming of dummy data.
- I simplified names for `waspello`, `waspleau`, `thoughts`, because I don't think those bigger names are needed any more now that we have README.md .
- I fixed some small mistakes/typos in the example cards on the landing page.
- I fixed links on the web/docs to examples to point to `release`, not `main`, since `release` is in sync with the latest released Wasp version, while `main` can contain whatever.

2023-11-07 10:56 UTC, sodic requested changes
I have no problem with the PR's goal, but that's mostly for @vincanger to comment on (the only reason I'm involved with the PR is merge conflict resolution).  As far as I'm concerned, short names make a lot of sense.

Aside from that, I've corrected a couple of errors and given some suggestions on improving the text.

Before submitting the PR, please go through the style guide (now that we finally have one :)). I think the style guide (and Grammarly, which the style guide prescribes) address all the mistakes and suggestions my comments mention. I know that this PR does not strictly fall under the "docs" category, but it's still something our users read. Therefore, the same rules should probably apply.

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +    - Demonstrates: **[optimistic updates](https://wasp-lang.dev/docs/data-model/operations/actions#the-useaction-hook-and-optimistic-updates)**, [auth](https://wasp-lang.dev/docs/auth/overview), [rp
Unless someone implemented this without me noticing, I don't believe it does :D

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +These are officially maintained example Wasp apps!
```suggestion
Here's a list of all officially maintained Wasp example apps!
```
Conveys the same message without relying on the text that follows.

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +Most of them are relatively small and demonstrate a couple of interesting Wasp features.
```suggestion
Most of these apps are relatively small, and each one demonstrates several of Wasp's interesting features.
```

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +**tutorials** dir contains [Wasp tutorial](https://wasp-lang.dev/docs/tutorial/create) apps.
```suggestion
The **tutorials** directory contains [Wasp tutorial](https://wasp-lang.dev/docs/tutorial/create) apps.
```

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +    - A simple task tracking app implemented in TypeScript.
```suggestion
    - A simple task-tracking app implemented in TypeScript.
```

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +    - A simple clone of Tableau; it regularly pulls in external data and shows it via nice dashboard.
```suggestion
    - A simple clone of Tableau. The app regularly pulls in external data and shows it on a nice dashboard.
```

2023-11-07 10:56 UTC, sodic commented on examples/README.md
> +    - Medium clone (https://github.com/gothinkster/realworld - mother of all demo apps).
```suggestion
    - A Medium clone (https://github.com/gothinkster/realworld - the mother of all demo apps).
```

2023-11-07 10:56 UTC, sodic commented on web/src/components/ExampleWaspApps.js
> +      'A realtime, websockets powered voting app built with Wasp in TypeScript.',
```suggestion
      'A realtime, websockets-powered voting app built with Wasp and TypeScript.',
```

2023-11-07 10:56 UTC, sodic commented on web/src/components/ExampleWaspApps.js
> +    description: 'Generate cover letters based on your CV and job description. Powered by ChatGPT.',
```suggestion
    description: 'Generate cover letters based on your CV and the job description. Powered by ChatGPT.',
```

2023-11-16 13:27 UTC, Martinsos commented
> I have no problem with the PR's goal, but that's mostly for @vincanger to comment on (the only reason I'm involved with the PR is merge conflict resolution). As far as I'm concerned, short names make a lot of sense.
> 
> Aside from that, I've corrected a couple of errors and given some suggestions on improving the text.
> 
> Before submitting the PR, please go through the style guide (now that we finally have one :)). I think the style guide (and Grammarly, which the style guide prescribes) address all the mistakes and suggestions my comments mention. I know that this PR does not strictly fall under the "docs" category, but it's still something our users read. Therefore, the same rules should probably apply.

Thanks for the review!

I didn't get what you mean by "the only reason I'm involved with the PR is merge conflict resolution", from what I saw what you did is fixed/improved grammar/wording, did I miss something?

Guilty here for not using Grammarly, I have to set it up in my editor. As for style guide - I want through all of it when I reviewed it, so I am aware of the concepts in it (although I am sure some I forgot), but it is not clear to me in this PR what I did wrong in regards to those -> it might help if you specifically point out those mistakes that you think went against docs style guide and are not just Grammarly fixes, so I can learn something from this.

2023-11-16 14:21 UTC, sodic approved these changes
All good on my side.

2023-11-17 09:07 UTC, vincanger commented
these names sound good and reasonable. My main aim was to make it easier for outsiders to understand what the Apps do, and the README does that.

2023-11-17 09:19 UTC, Martinsos commented
> these names sound good and reasonable. My main aim was to make it easier for outsiders to understand what the Apps do, and the README does that.

Awesome, I am glad to hear that! I will then resolve the conflicts and comments and merge.

2023-11-17 14:02 UTC, merged