Handle case when JWT token verification fails
wasp-lang/wasp pull request #177
Opened 2021-02-08 03:05 UTC by jpcarroll

# Description

Handles the case when JWT token verification fails by sending a 401 instead of a 500 and deleting the JWT token from local storage.

Fixes # (168)

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-02-08 21:01 UTC, Martinsos commented
Awesome, great job :)!!
While the resulting code is not so big, I am sure you put some decent effort into getting Wasp running for the first time -> how was that for you? Any feedback that might help future contributors?

Regarding the PR, I would suggest one change: right now, you are capturing all errors and returning 401. Tricky part when catching any error is that error could be some unexpected error, for example syntax error or something else that was not caused by invalid token, and we will still report it as 401. I took a quick look at https://github.com/auth0/node-jsonwebtoken#errors--codes and I see that the returned error can be of 3 different types. I suggest we check if error is any of those, if so, we return 401, otherwise we just re-throw it. Let me know if this makes sense or not!

Oh, and regarding testing -> very good point. The best way to test generated (like this one) would probably be to also have Wasp generate tests along it, and then we would run them when we generate the code (when appropriate). Unfortunately, we don't have this set up yet since we are in alpha and are putting focus on moving quickly, but we will certainly have it at some point because it is becoming harder to ensure quality.

2021-02-08 21:03 UTC, Martinsos requested changes
Great! Let's just see if we can make error handling logic more specific, and we are good to go.

2021-02-08 22:00 UTC, jpcarroll commented
Ok I added checks for the different error types and rethrowing error otherwise. I decided to check for the error name in the object using regex but I wonder if there is a better/more readable way of doing this without doing this abomination
`if (error.name == TokenExpiredError  || error.name == JsonWebTokenError || error.name == NotBeforeError)`. Any thoughts?

2021-02-09 10:25 UTC, Martinsos commented
> Ok I added checks for the different error types and rethrowing error otherwise. I decided to check for the error name in the object using regex but I wonder if there is a better/more readable way of doing this without doing this abomination
> `if (error.name == 'TokenExpiredError' || error.name == 'JsonWebTokenError' || error.name == 'NotBeforeError')`.
> Any thoughts?

Regex is not bad, but it is probably overly complex for this use case, I would suggest going with:
```js
if (['TokenExpiredError', 'JsonWebTokenError', 'NotBeforeError'].includes(error.name))
```
```

2021-02-09 10:32 UTC, Martinsos commented on waspc/data/Generator/templates/server/src/core/auth.js
> +      }
```suggestion
      } else {
        throw error
      }
```

2021-02-09 10:33 UTC, Martinsos requested changes
Almost there! TODO:
1. regex -> .includes
2.  console.error -> throw

2021-02-09 15:59 UTC, Martinsos commented
@jpcarroll while I was testing I figured out that axios interceptor was not actually executing!
How I tested it -> I ran wasp Todo App (one from waspc/examples/todoApp) and after I created one user, I deleted it (via `wasp db studio`). Then, server produced error 401 since user with such ID does not exist, however token was not getting cleared on the frontend. I then checked the axios docs and it turns out, when providing response interceptor, you can actually provide two functions: one for the response, and one for the error. First one handles only response with status 2xx, other one handles the rest (errors). So we were checking if response has status 401 in a callback function that only received response with status 2xx, so that never happened. Therefore, I provided the second functions as per axios docs and did the same thing there, and now it works!
Small thing: I also replaced `var` with `let` on the server, it does not change how code works but it is a good practice to not use `var`.

Anyway, this should be it now! I will be merging it now :).

2021-02-09 16:00 UTC, merged