Account for recent changes in docs and example apps
wasp-lang/wasp pull request #808
Opened 2022-11-09 11:27 UTC by sodic

Updates the example apps with recent changes to the project structure.

2022-11-09 17:31 UTC, shayneczyzewski requested changes
Awesome attention to detail here, @sodic. I know it was a lot of effort to get all this updated. Nice job!

One page I noticed that still references `@ext` is the main page `web/src/pages/index.js`, as does one line in `features.md` (`js title="ext/myClientSetupCode.js"`)

I tried to drop in suggested edits where I thought they made sense, but even my eyes could not be trusted near the end of reviewing it all haha :D It all becomes very sneaky/subtle, so take them with a grain of salt. I will do another review with fresh eyes after you have a chance to check out the ideas here. 👍🏻

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/syntax.md
> +      - The path start with "@server". The rest is relative to the `src/server` directory.
```suggestion
      - The path has to start with "@server". The rest is relative to the `src/server` directory.
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/listing-tasks.md
> +  // can be found in `@server/queries.js` as the named export `getTasks`.
Should this be the path (`src/server`) instead of the import?

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/listing-tasks.md
> +We've just said that the queries we write are executed on the server, but Wasp will generate client-side querie functions (taking care of the network and cache invalidation in the background). Let's
```suggestion
We've just said that the queries we write are executed on the server, but Wasp will generate client-side query functions (taking care of the network and cache invalidation in the background). Let's finally use the query we've just created, `getTasks`, in our React component to list the tasks:
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/creating-new-project.md
> +  // `@client/MainPage.js` as a default export (uses standard js import syntax).
Should this be the path `src/client` instead of import syntax?

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/creating-new-project.md
> +Wasp quitely takes care of everything else needed to define, build, and run a web app.
```suggestion
Wasp quietly takes care of everything else needed to define, build, and run a web app.
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/creating-new-project.md
> +To prepare the clean slate for building the TodoApp, the files `Main.css` and `waspLogo.png` from the `src/client/` folder (`src/shared` and `src/server` are already clean). The `jsconfig.json` files
Should this say "delete the files"?

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/creating-new-project.md
> +To prepare the clean slate for building the TodoApp, the files `Main.css` and `waspLogo.png` from the `src/client/` folder (`src/shared` and `src/server` are already clean). The `jsconfig.json` files
```suggestion
To prepare the clean slate for building the TodoApp, the files `Main.css` and `waspLogo.png` from the `src/client/` folder (`src/shared` and `src/server` are already clean). The `jsconfig.json` files are necessary for IDE support, so it's important to keep them. Now that `src/client` contains only `jsconfig.json` and `MainPage.js` let's start by making the `MainPage` component much simpler:
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/features.md
> +Wasp compiler configuration. It is a dictionary a single field:
```suggestion
Wasp compiler configuration. It is a dictionary with a single field:
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/features.md
> +```jsx title="client/pages/OtherPage.js"
Do we want to be explicit here and put `src/` in front?

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/features.md
> +  fn: import { getAllTasks } from "@src/server/queries.js",
```suggestion
  fn: import { getAllTasks } from "@server/queries.js",
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/features.md
> +  fn: import { getFilteredTasks } from "@src/server/queries.js",
```suggestion
  fn: import { getFilteredTasks } from "@server/queries.js",
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/features.md
> +```js title="client/pages/MainPage.js"
```suggestion
```js title="src/client/pages/MainPage.js"
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/language/features.md
> +```js {4,18} title=client/pages/Task.js
I know the previous versions just used `pages`, but do we want to always preface with `src/` moving forward?

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/auth.md
> +```js {1,4,6} title="@server/queries.js"
```suggestion
```js {1,4,6} title="src/server/queries.js"
```

2022-11-09 17:31 UTC, shayneczyzewski commented on web/docs/tutorials/todo-app/auth.md
> +```js {1,4,8,14,15,16} title="@server/actions.js"
```suggestion
```js {1,4,8,14,15,16} title="src/server/actions.js"
```

2022-11-09 18:30 UTC, sodic commented on web/docs/language/features.md
> -## Compiler configuration
Yeah, I moved it to the start together with other fields in the `app` declaration.

2022-11-09 18:32 UTC, sodic commented
Wow @shayneczyzewski, thanks for noticing all of those. I thought I went through it a couple of times, but I guess I was too tired and biased to see it. I'll implement all the changes and mark your comments with :rocket: when they're up.

2022-11-10 00:36 UTC, sodic commented on web/docs/tutorials/todo-app/creating-new-project.md
> +│   ├── client            # Our external client code (JS/CSS/HTML) goes here.
Much better, thanks!

2022-11-10 10:56 UTC, sodic commented
> One page I noticed that still references `@ext` is the main page `web/src/pages/index.js`, as does one line in `features.md` (`js title="ext/myClientSetupCode.js"`)

Crap, forgot about the blogs :sweat_smile: 
![image](https://user-images.githubusercontent.com/22752307/201072344-3e2e253f-4ef1-42e5-b0a7-6de552550798.png)

I'll have it ready by tomorrow and let you know. The other stuff you mentioned is fixed and pushed.

2022-11-11 13:46 UTC, sodic commented
@shayneczyzewski Ok, all done:
- Some of your comments have been autoresolved when I committed your suggestions, so don't worry about opening resolved threads (I haven't resolved any of them manually).
- The ones I resolved and pushed manually are marked with a rocket (:rocket:), but I haven't resolved them
- I've also updated a few other files we've missed. Blog updates and Changelog edits are covered by PR #809

2022-11-11 14:50 UTC, shayneczyzewski approved these changes
Awesome job here @sodic. A TON of effort to update all this, so well done 👏🏻 Two minor things but looks ready to roll to me 👍🏻 Great job

2022-11-11 14:50 UTC, shayneczyzewski commented on web/docs/language/features.md
> +```jsx {3,9,10,11,12,13,14,15,16,27} title=client/pages/Task.js
```suggestion
```jsx {3,9,10,11,12,13,14,15,16,27} title=src/client/pages/Task.js
```

2022-11-11 14:50 UTC, shayneczyzewski commented on web/src/pages/index.js
> +          <CodeBlockWithTitle title="@client/Todo.js | Invoking query from React code" language="jsx">
```suggestion
          <CodeBlockWithTitle title="src/client/Todo.js | Invoking query from React code" language="jsx">
```

2022-11-11 17:36 UTC, merged